export const resorts = [
  {
    id: "verbier",
    name: "Verbier",
    country: "Switzerland",
    countryCode: "CH",
    flag: "🇨🇭",
    rating: 9.1,
    ratingLabel: "Exceptional",
    priceFrom: 62,
    pisteKm: 412,
    maxAltitude: 3330,
    minAltitude: 1500,
    runs: 94,
    lifts: 38,
    difficulty: ["intermediate", "expert"],
    facilities: ["terrain_park", "night_skiing"],
    image: "https://picsum.photos/seed/verbier/800/500",
    images: [
      "https://picsum.photos/seed/verbier1/1200/600",
      "https://picsum.photos/seed/verbier2/1200/600",
      "https://picsum.photos/seed/verbier3/1200/600",
    ],
    description: "Verbier is one of the premier freeride destinations in the world, set in the heart of the Swiss Alps. Known for its challenging off-piste terrain, vibrant après-ski scene, and breathtaking panoramic views of Mont Blanc and the Grand Combin. The resort offers a perfect blend of extreme skiing and luxurious mountain living.",
    weather: { temp: -8, snowDepth: 185, condition: "Snowy", forecast: [
      { day: "Today", high: -6, low: -12, condition: "snow" },
      { day: "Tomorrow", high: -4, low: -10, condition: "partly_cloudy" },
      { day: "Thu", high: -7, low: -14, condition: "snow" },
    ]},
    reviews: {
      overall: 9.1,
      breakdown: { pistes: 9.2, lifts: 8.8, apresSki: 9.4, value: 8.5, beginners: 7.2 },
      items: [
        { id: 1, name: "Marcus Lindqvist", avatar: "https://picsum.photos/seed/user1/100/100", flag: "🇸🇪", date: "Feb 2026", rating: 9.5, text: "Absolutely world-class freeride terrain. The Mont Fort descent is something every advanced skier needs to experience. Après-ski scene is electric." },
        { id: 2, name: "Sophie Müller", avatar: "https://picsum.photos/seed/user2/100/100", flag: "🇩🇪", date: "Jan 2026", rating: 8.8, text: "Beautiful resort with incredible views. Lifts can get crowded on weekends but the skiing makes up for it. The new Médran gondola is fantastic." },
        { id: 3, name: "James Harrison", avatar: "https://picsum.photos/seed/user3/100/100", flag: "🇬🇧", date: "Mar 2026", rating: 9.0, text: "Our family's favourite resort. While it's known for expert terrain, there are great intermediate runs too. Kids loved the ski school." },
      ]
    },
    liftPasses: [
      { type: "1-day", adult: 62, child: 31, senior: 50, badge: null },
      { type: "3-day", adult: 168, child: 84, senior: 135, badge: "Best value" },
      { type: "6-day", adult: 310, child: 155, senior: 248, badge: null },
      { type: "Season", adult: 1450, child: 725, senior: 1160, badge: null },
    ],
    instructors: [
      { id: 1, name: "Pierre Dubois", avatar: "https://picsum.photos/seed/inst1/200/200", languages: ["French", "English", "German"], rating: 4.9, speciality: "Freeride · Expert", aiMatch: true },
      { id: 2, name: "Elena Rossi", avatar: "https://picsum.photos/seed/inst2/200/200", languages: ["Italian", "English", "French"], rating: 4.7, speciality: "Freestyle · Advanced", aiMatch: false },
      { id: 3, name: "Thomas Keller", avatar: "https://picsum.photos/seed/inst3/200/200", languages: ["German", "English"], rating: 4.8, speciality: "Technique · Intermediate", aiMatch: false },
    ]
  },
  {
    id: "val-thorens",
    name: "Val Thorens",
    country: "France",
    countryCode: "FR",
    flag: "🇫🇷",
    rating: 8.8,
    ratingLabel: "Excellent",
    priceFrom: 54,
    pisteKm: 600,
    maxAltitude: 3230,
    minAltitude: 1800,
    runs: 78,
    lifts: 32,
    difficulty: ["beginner", "intermediate"],
    facilities: ["terrain_park", "kids_area"],
    image: "https://picsum.photos/seed/valthorens/800/500",
    images: [
      "https://picsum.photos/seed/valthorens1/1200/600",
      "https://picsum.photos/seed/valthorens2/1200/600",
      "https://picsum.photos/seed/valthorens3/1200/600",
    ],
    description: "As the highest resort in Europe, Val Thorens guarantees exceptional snow conditions throughout the season. Part of the massive Trois Vallées ski area — the largest linked ski domain in the world.",
    weather: { temp: -11, snowDepth: 220, condition: "Clear", forecast: [
      { day: "Today", high: -9, low: -15, condition: "clear" },
      { day: "Tomorrow", high: -7, low: -13, condition: "clear" },
      { day: "Thu", high: -10, low: -16, condition: "snow" },
    ]},
    reviews: { overall: 8.8, breakdown: { pistes: 9.0, lifts: 8.5, apresSki: 8.8, value: 8.9, beginners: 9.0 }, items: [] },
    liftPasses: [
      { type: "1-day", adult: 54, child: 27, senior: 43, badge: null },
      { type: "3-day", adult: 145, child: 73, senior: 116, badge: "Best value" },
      { type: "6-day", adult: 270, child: 135, senior: 216, badge: null },
      { type: "Season", adult: 1200, child: 600, senior: 960, badge: null },
    ],
    instructors: []
  },
  {
    id: "st-anton",
    name: "St. Anton",
    country: "Austria",
    countryCode: "AT",
    flag: "🇦🇹",
    rating: 8.6,
    ratingLabel: "Excellent",
    priceFrom: 58,
    pisteKm: 305,
    maxAltitude: 2811,
    minAltitude: 1304,
    runs: 88,
    lifts: 34,
    difficulty: ["intermediate", "expert"],
    facilities: ["terrain_park", "night_skiing"],
    image: "https://picsum.photos/seed/stanton/800/500",
    images: [
      "https://picsum.photos/seed/stanton1/1200/600",
      "https://picsum.photos/seed/stanton2/1200/600",
      "https://picsum.photos/seed/stanton3/1200/600",
    ],
    description: "The birthplace of alpine skiing, St. Anton am Arlberg remains one of Austria's most legendary resorts. Famous for its challenging terrain, legendary après-ski, and authentic Tyrolean charm.",
    weather: { temp: -5, snowDepth: 160, condition: "Partly cloudy", forecast: [
      { day: "Today", high: -3, low: -9, condition: "partly_cloudy" },
      { day: "Tomorrow", high: -2, low: -8, condition: "partly_cloudy" },
      { day: "Thu", high: -5, low: -11, condition: "snow" },
    ]},
    reviews: { overall: 8.6, breakdown: { pistes: 8.5, lifts: 8.3, apresSki: 9.5, value: 8.2, beginners: 7.5 }, items: [] },
    liftPasses: [
      { type: "1-day", adult: 58, child: 29, senior: 46, badge: null },
      { type: "3-day", adult: 158, child: 79, senior: 126, badge: "Best value" },
      { type: "6-day", adult: 295, child: 148, senior: 236, badge: null },
      { type: "Season", adult: 1350, child: 675, senior: 1080, badge: null },
    ],
    instructors: []
  },
  {
    id: "zermatt",
    name: "Zermatt",
    country: "Switzerland",
    countryCode: "CH",
    flag: "🇨🇭",
    rating: 9.3,
    ratingLabel: "Exceptional",
    priceFrom: 71,
    pisteKm: 360,
    maxAltitude: 3883,
    minAltitude: 1620,
    runs: 72,
    lifts: 52,
    difficulty: ["beginner", "intermediate", "expert"],
    facilities: ["kids_area"],
    image: "https://picsum.photos/seed/zermatt/800/500",
    images: [
      "https://picsum.photos/seed/zermatt1/1200/600",
      "https://picsum.photos/seed/zermatt2/1200/600",
      "https://picsum.photos/seed/zermatt3/1200/600",
    ],
    description: "Dominated by the iconic Matterhorn, Zermatt offers year-round skiing in a car-free village setting. One of the highest and most snow-sure resorts in the Alps with cross-border skiing into Cervinia, Italy.",
    weather: { temp: -10, snowDepth: 200, condition: "Snowy", forecast: [
      { day: "Today", high: -8, low: -14, condition: "snow" },
      { day: "Tomorrow", high: -6, low: -12, condition: "partly_cloudy" },
      { day: "Thu", high: -9, low: -15, condition: "clear" },
    ]},
    reviews: { overall: 9.3, breakdown: { pistes: 9.4, lifts: 9.2, apresSki: 8.8, value: 8.0, beginners: 8.5 }, items: [] },
    liftPasses: [
      { type: "1-day", adult: 71, child: 36, senior: 57, badge: null },
      { type: "3-day", adult: 195, child: 98, senior: 156, badge: "Best value" },
      { type: "6-day", adult: 365, child: 183, senior: 292, badge: null },
      { type: "Season", adult: 1600, child: 800, senior: 1280, badge: null },
    ],
    instructors: []
  },
  {
    id: "cortina",
    name: "Cortina d'Ampezzo",
    country: "Italy",
    countryCode: "IT",
    flag: "🇮🇹",
    rating: 8.4,
    ratingLabel: "Very Good",
    priceFrom: 48,
    pisteKm: 140,
    maxAltitude: 2930,
    minAltitude: 1224,
    runs: 65,
    lifts: 28,
    difficulty: ["beginner", "intermediate"],
    facilities: ["kids_area", "night_skiing"],
    image: "https://picsum.photos/seed/cortina/800/500",
    images: [
      "https://picsum.photos/seed/cortina1/1200/600",
      "https://picsum.photos/seed/cortina2/1200/600",
      "https://picsum.photos/seed/cortina3/1200/600",
    ],
    description: "The 'Queen of the Dolomites', Cortina d'Ampezzo combines world-class skiing with Italian glamour. Host of the 2026 Winter Olympics, the resort features stunning Dolomite scenery and excellent cuisine.",
    weather: { temp: -3, snowDepth: 130, condition: "Clear", forecast: [
      { day: "Today", high: -1, low: -7, condition: "clear" },
      { day: "Tomorrow", high: 0, low: -6, condition: "clear" },
      { day: "Thu", high: -3, low: -9, condition: "partly_cloudy" },
    ]},
    reviews: { overall: 8.4, breakdown: { pistes: 8.2, lifts: 7.8, apresSki: 8.8, value: 8.8, beginners: 9.0 }, items: [] },
    liftPasses: [
      { type: "1-day", adult: 48, child: 24, senior: 38, badge: null },
      { type: "3-day", adult: 130, child: 65, senior: 104, badge: "Best value" },
      { type: "6-day", adult: 245, child: 123, senior: 196, badge: null },
      { type: "Season", adult: 1100, child: 550, senior: 880, badge: null },
    ],
    instructors: []
  },
  {
    id: "courchevel",
    name: "Courchevel",
    country: "France",
    countryCode: "FR",
    flag: "🇫🇷",
    rating: 8.9,
    ratingLabel: "Excellent",
    priceFrom: 66,
    pisteKm: 600,
    maxAltitude: 2738,
    minAltitude: 1300,
    runs: 102,
    lifts: 58,
    difficulty: ["beginner", "intermediate", "expert"],
    facilities: ["terrain_park", "kids_area", "night_skiing"],
    image: "https://picsum.photos/seed/courchevel/800/500",
    images: [
      "https://picsum.photos/seed/courchevel1/1200/600",
      "https://picsum.photos/seed/courchevel2/1200/600",
      "https://picsum.photos/seed/courchevel3/1200/600",
    ],
    description: "Part of the world's largest ski area, Les 3 Vallées, Courchevel offers unmatched variety across its five villages. From luxury Courchevel 1850 to family-friendly Le Praz, there's something for every skier.",
    weather: { temp: -6, snowDepth: 175, condition: "Partly cloudy", forecast: [
      { day: "Today", high: -4, low: -10, condition: "partly_cloudy" },
      { day: "Tomorrow", high: -3, low: -9, condition: "clear" },
      { day: "Thu", high: -6, low: -12, condition: "snow" },
    ]},
    reviews: { overall: 8.9, breakdown: { pistes: 9.1, lifts: 9.0, apresSki: 8.7, value: 7.8, beginners: 9.2 }, items: [] },
    liftPasses: [
      { type: "1-day", adult: 66, child: 33, senior: 53, badge: null },
      { type: "3-day", adult: 180, child: 90, senior: 144, badge: "Best value" },
      { type: "6-day", adult: 335, child: 168, senior: 268, badge: null },
      { type: "Season", adult: 1500, child: 750, senior: 1200, badge: null },
    ],
    instructors: []
  }
];

export const trendingCards = [
  { id: "zermatt", resort: "Zermatt", tag: "Best powder in the Alps", image: "https://picsum.photos/seed/trending1/600/400" },
  { id: "val-thorens", resort: "Val Thorens", tag: "Top-rated for progression", image: "https://picsum.photos/seed/trending2/600/400" },
  { id: "courchevel", resort: "Courchevel", tag: "Ultimate luxury skiing", image: "https://picsum.photos/seed/trending3/600/400" },
];

export const dashboardData = {
  userName: "Alex",
  totalDays: 14,
  resortsVisited: 4,
  runsLogged: 187,
  verticalMetres: 142800,
  lastSeasonVertical: 98500,
  upcomingTrip: {
    resort: "Verbier",
    dates: "Mar 15 – Mar 21, 2026",
    passType: "6-day pass",
    daysAway: 14,
  },
  savedResorts: ["zermatt", "courchevel", "val-thorens"],
  recentActivity: [
    { action: "Booked Verbier 6-day lift pass", time: "2 hours ago", icon: "ticket" },
    { action: "Saved Zermatt to favourites", time: "1 day ago", icon: "heart" },
    { action: "Logged 3 runs via GPS tracking", time: "3 days ago", icon: "map" },
    { action: "Left a review for St. Anton", time: "5 days ago", icon: "star" },
  ]
};

export function getResortById(id) {
  return resorts.find(r => r.id === id);
}