export const hotels = [
  {
    id: "hotel-kitzhof",
    name: "Hotel Kitzhof Mountain Design Resort",
    slug: "hotel-kitzhof",
    stars: 4,
    category: "4 Sterne Superior",
    address: "Schwarzseestrasse 8-10",
    city: "Kitzbühel",
    country: "Austria",
    countryCode: "AT",
    flag: "🇦🇹",
    coordinates: { lat: 47.4472, lon: 12.3913 },
    phone: "+43 5356 63211-0",
    email: "info@hotel-kitzhof.com",
    website: "www.hotel-kitzhof.com",
    description: "Hotel Kitzhof Mountain Design Resort is a 4 Sterne Superior hotel located directly on the city park of Kitzbühel, with panoramic views of the Kitzbüheler Horn and the legendary Hahnenkamm. Just a few minutes walk from the picturesque centre of this famous Tyrolean resort, the hotel combines stylish alpine design with genuine Tyrolean warmth. The design concept by Munich interior designer Ursula Schelle-Müller blends generous use of glass and natural daylight with mountain larch wood floors, reclaimed timber panelling, modern furniture upholstered in grey and red loden, open fireplaces, antler decorations and designer lighting. The result redefines Tyrolean Gemütlichkeit for the contemporary traveller. Member of Preferred Hotels and Resorts L.V.X. Collection.",
    shortDescription: "4-star superior mountain design resort in Kitzbühel — steps from the Hahnenkamm, walk to the lifts.",
    logo: "https://media.base44.com/images/public/69f1c737747c83c0b091a543/1d289c8f4_Bildschirmfoto_30-4-2026_205344_.jpg",
    images: [
      "https://media.base44.com/images/public/69f1c737747c83c0b091a543/18c29298b_AuenansichtfrontHotelKitzhof.jpg",
      "https://media.base44.com/images/public/69f1c737747c83c0b091a543/0bd8137f1_AuenansichtGartenHotelKitzhof.jpg",
      "https://media.base44.com/images/public/69f1c737747c83c0b091a543/8fca7a304_AuenansichtTerrasse2HotelKitzhof.jpg",
      "https://media.base44.com/images/public/69f1c737747c83c0b091a543/b750cb336_PoolHotelKitzhof.jpg",
      "https://media.base44.com/images/public/69f1c737747c83c0b091a543/a28bfe685_PoolLiegebereichHotelKitzhof.jpg",
      "https://media.base44.com/images/public/69f1c737747c83c0b091a543/52d461bad_RuhebereichHotelKitzhof.jpg",
      "https://media.base44.com/images/public/69f1c737747c83c0b091a543/b039fe118_KitzhofRestaurantHotelKitzhof.jpg",
      "https://media.base44.com/images/public/69f1c737747c83c0b091a543/92656e197_KaminstubeHotelKitzhof.jpg",
      "https://media.base44.com/images/public/69f1c737747c83c0b091a543/8a51bc3a6_VinothekHotelKitzhof.jpg",
      "https://media.base44.com/images/public/69f1c737747c83c0b091a543/e71315b1e_KitzLoungeKaminbereichHotelKitzhof.jpg",
      "https://media.base44.com/images/public/69f1c737747c83c0b091a543/6072023dc_ChampagnerfrhstckaufderTerrasseHotelKitzhof.jpg",
      "https://media.base44.com/images/public/69f1c737747c83c0b091a543/00ad3ef63_Terrasse2HotelKitzhof.jpg",
      "https://media.base44.com/images/public/69f1c737747c83c0b091a543/40945f6bb_DZSuperiorKitzbhelHotelKitzhof.jpg",
      "https://media.base44.com/images/public/69f1c737747c83c0b091a543/b97aefb97_AlpinSuiteHotelKitzhof.jpg",
      "https://media.base44.com/images/public/69f1c737747c83c0b091a543/0a316aaaf_AlpinSuite2HotelKitzhof.jpg",
      "https://media.base44.com/images/public/69f1c737747c83c0b091a543/9edcff9dc_StudioHotelKitzhof.jpg",
      "https://media.base44.com/images/public/69f1c737747c83c0b091a543/863e5ddd0_StudioSuite2HotelKitzhof.jpg",
      "https://media.base44.com/images/public/69f1c737747c83c0b091a543/eb142cddd_GardenSuiteHotelKitzhof.jpg",
      "https://media.base44.com/images/public/69f1c737747c83c0b091a543/580829ff4_KitzhofSuite2HotelKitzhof.jpg",
    ],
    priceFrom: 195,
    currency: "EUR",
    rating: 0,
    ratingLabel: "No reviews yet",
    reviewCount: 0,
    amenities: [
      "Indoor Pool", "Spa 900m²", "Free WiFi", "Restaurant", "Bar / Lounge",
      "Fitness Centre", "Underground Parking", "Conference Rooms",
      "Ski Storage", "Hotel Shuttle", "Sauna Landscape", "Fireplace Lounge",
      "Garden", "Terrace", "Room Service", "Concierge", "Wine Cellar",
    ],
    totalRooms: 122,
    totalSuites: 38,
    rooms: [
      { id: "dz-kitz", name: "Double Superior Kitzbühel", description: "Panoramic views of Kitzbühel and surroundings. Alpine design with mountain larch floors.", size: null, maxGuests: 2, pricePerNight: 195, images: ["https://media.base44.com/images/public/69f1c737747c83c0b091a543/40945f6bb_DZSuperiorKitzbhelHotelKitzhof.jpg"], amenities: ["Free WiFi", "Minibar", "Safe", "Flat-screen TV", "Raindance shower", "Telephone"], available: true },
      { id: "dz-streif", name: "Double Superior Streif", description: "Named after the legendary Hahnenkamm Streif downhill course. Premium alpine finishes.", size: null, maxGuests: 2, pricePerNight: 215, images: ["https://media.base44.com/images/public/69f1c737747c83c0b091a543/40945f6bb_DZSuperiorKitzbhelHotelKitzhof.jpg"], amenities: ["Free WiFi", "Minibar", "Safe", "Flat-screen TV", "Raindance shower", "Telephone"], available: true },
      { id: "dz-lebenberg", name: "Double Superior Lebenberg", description: "Views of the Lebenberg castle. Warm alpine atmosphere with reclaimed timber detail.", size: null, maxGuests: 2, pricePerNight: 205, images: ["https://media.base44.com/images/public/69f1c737747c83c0b091a543/40945f6bb_DZSuperiorKitzbhelHotelKitzhof.jpg"], amenities: ["Free WiFi", "Minibar", "Safe", "Flat-screen TV", "Raindance shower", "Telephone"], available: true },
      { id: "junior-suite", name: "Junior Suite", description: "Spacious junior suite with separate living area. Ideal for couples seeking extra space.", size: null, maxGuests: 2, pricePerNight: 285, images: ["https://media.base44.com/images/public/69f1c737747c83c0b091a543/b97aefb97_AlpinSuiteHotelKitzhof.jpg"], amenities: ["Free WiFi", "Minibar", "Safe", "Flat-screen TV", "Raindance shower", "Separate living area"], available: true },
      { id: "studio", name: "Studio", description: "Top-floor studio with Velux skylights offering views of the mountain landscape.", size: null, maxGuests: 2, pricePerNight: 265, images: ["https://media.base44.com/images/public/69f1c737747c83c0b091a543/9edcff9dc_StudioHotelKitzhof.jpg"], amenities: ["Free WiFi", "Minibar", "Safe", "Flat-screen TV", "Skylight windows", "Raindance shower"], available: true },
      { id: "alpin-suite", name: "Alpin Suite", description: "Generous suite with separate living room and full alpine design concept.", size: null, maxGuests: 3, pricePerNight: 345, images: ["https://media.base44.com/images/public/69f1c737747c83c0b091a543/b97aefb97_AlpinSuiteHotelKitzhof.jpg"], amenities: ["Free WiFi", "Minibar", "Safe", "Flat-screen TV", "Separate living room", "Raindance shower"], available: true },
      { id: "studio-suite", name: "Studio Suite", description: "Top-floor suite with premium finishes, skylights and panoramic mountain views.", size: null, maxGuests: 3, pricePerNight: 365, images: ["https://media.base44.com/images/public/69f1c737747c83c0b091a543/863e5ddd0_StudioSuite2HotelKitzhof.jpg"], amenities: ["Free WiFi", "Minibar", "Safe", "Flat-screen TV", "Skylight", "Raindance shower"], available: true },
      { id: "lebenberg-suite", name: "Lebenberg Suite", description: "Named after the Lebenberg — generous suite with classic Tyrolean mountain views.", size: null, maxGuests: 4, pricePerNight: 385, images: ["https://media.base44.com/images/public/69f1c737747c83c0b091a543/0a316aaaf_AlpinSuite2HotelKitzhof.jpg"], amenities: ["Free WiFi", "Minibar", "Safe", "Flat-screen TV", "Separate living area", "Raindance shower"], available: true },
      { id: "garden-suite", name: "Garden Suite", description: "Private garden access. Built in 2019 and extended 2023. East wing location with serene views.", size: null, maxGuests: 4, pricePerNight: 425, images: ["https://media.base44.com/images/public/69f1c737747c83c0b091a543/eb142cddd_GardenSuiteHotelKitzhof.jpg"], amenities: ["Free WiFi", "Minibar", "Safe", "Flat-screen TV", "Private garden", "Raindance shower"], available: true },
      { id: "kitzhof-suite", name: "Kitzhof Suite", description: "The hotel's flagship suite. Suitable for boardroom use. Ultimate luxury in Kitzbühel.", size: null, maxGuests: 4, pricePerNight: 550, images: ["https://media.base44.com/images/public/69f1c737747c83c0b091a543/580829ff4_KitzhofSuite2HotelKitzhof.jpg"], amenities: ["Free WiFi", "Minibar", "Safe", "Flat-screen TV", "Boardroom setup possible", "Raindance shower", "Butler service"], available: true },
    ],
    restaurants: [
      { name: "Weisser Hirsch", cuisine: "Austrian / International", seats: 100, description: "The main restaurant of Hotel Kitzhof, offering Austrian and international cuisine in an elegant alpine setting.", reservationRequired: false },
      { name: "Kaminstube", cuisine: "Alpine", seats: 65, description: "Cosy fireplace room serving hearty alpine dishes. Ideal for evenings after a day on the slopes.", reservationRequired: true },
      { name: "Kitz Alm", cuisine: "Tyrolean", seats: 50, description: "Rustic mountain hut-style dining featuring traditional Tyrolean specialities.", reservationRequired: false },
      { name: "Hornstube", cuisine: "Fine Dining", seats: 30, description: "Intimate fine dining room with a focused seasonal menu and attentive service.", reservationRequired: true },
      { name: "Vinothek", cuisine: "Wine Bar", seats: 16, description: "A walk-in wine cellar featuring an exceptional selection of Austrian and international wines.", reservationRequired: false },
      { name: "Jagdstube", cuisine: "Private Dining", seats: 15, description: "Exclusive private dining room in hunting lodge style — ideal for special occasions.", reservationRequired: true },
      { name: "Kitz Lounge", cuisine: "Bar", seats: 40, description: "The social heart of the hotel — cocktails, après-ski, and a warm fireplace atmosphere.", reservationRequired: false },
    ],
    spa: {
      description: "The Kitz Spa spans 900 sqm with a 15x5m indoor pool with experience showers, relaxation area and winter garden. Sauna landscape includes steam bath, brine steam bath, Swiss pine sauna and sanarium with relaxation room and fireplace. Five treatment rooms with Susanne Kaufmann products. Life Fitness gym equipment.",
      poolSize: "15 × 5 m",
      sqm: 900,
      saunaTypes: ["Steam bath", "Brine steam bath", "Swiss pine sauna (Zirbensauna)", "Sanarium"],
      treatments: "5 treatment rooms — Susanne Kaufmann product range",
      fitnessEquipment: "Life Fitness branded equipment",
    },
    events: {
      maxCapacity: 400,
      roomCount: 9,
      largestRoomSqm: 340,
      description: "The Kitzbüheler Alpen conference area comprises five rooms on the garden level, four with direct garden access. Can be combined into one large hall of 340 sqm. Also Davos, Lech, St. Moritz rooms and Kitzhof Suite for smaller meetings.",
      rooms: [
        { name: "Kitzbüheler Alpen", capacity: 400, sqm: 340, features: "5 combinable rooms, direct garden access" },
        { name: "Davos", capacity: 40, sqm: 60, features: "Breakout room" },
        { name: "Lech", capacity: 40, sqm: 60, features: "Breakout room" },
        { name: "St. Moritz", capacity: 40, sqm: 60, features: "Breakout room" },
        { name: "Kitzhof Suite", capacity: 20, sqm: null, features: "Boardroom / private meeting" },
      ],
    },
    parking: { available: true, type: "Underground garage, on-site", pricePerDay: 18, includedInPass: false },
    policies: {
      checkIn: "15:00",
      checkOut: "11:00",
      pets: "On request",
      smoking: "No smoking in rooms — designated outdoor areas only",
      children: "Children of all ages welcome",
      cancellation: "Varies by rate — see booking conditions at time of reservation",
      deposit: "Credit card required at check-in",
    },
    sustainability: {
      certifications: [],
      notes: "Committed to local Austrian produce and regional suppliers. Energy efficiency measures ongoing.",
    },
    nearbyAttractions: [
      { name: "Hahnenkamm gondola", distanceKm: 0.6, type: "Ski Lift" },
      { name: "Kitzbühel town centre", distanceKm: 0.3, type: "Shopping & Dining" },
      { name: "Kitzbüheler Horn cable car", distanceKm: 1.2, type: "Ski Lift" },
      { name: "Golf Club Kitzbühel", distanceKm: 2, type: "Golf" },
    ],
    publicTransport: { nearestStation: "Kitzbühel train station", distanceKm: 0.8, shuttleAvailable: true },
    history: [
      { year: "1993/94", event: "Purchase and conversion of the old Hotel Hirzinger Hof" },
      { year: "December 1994", event: "Opening as Astron Sporthotel Kitzbühel" },
      { year: "2005", event: "Repositioned as individual hotel under the name Hotel Kitzhof" },
      { year: "2005–2008", event: "Continuous expansion, renovation and conversion works to the current Hotel Kitzhof Mountain Design Resort" },
      { year: "2014", event: "Top floor expansion adding Studio room category" },
      { year: "2015", event: "Top floor expansion adding Alpin Suites, Studio Suites and Lebenberg Suites" },
      { year: "2016", event: "New Double Superior Streif rooms and Junior Suites" },
      { year: "2017", event: "Expansion of sauna landscape and relaxation area" },
      { year: "2018", event: "Refresh of Double Superior Lebenberg and Superior Kitzbühel rooms, Lebenberg Suites, redesign of Kitz Lounge" },
      { year: "2019", event: "East wing conversion, new Garden Suites completed, new modern fitness wing built" },
      { year: "2023", event: "Room renovations, two additional Garden Suites built, new lobby and conference area completed" },
    ],
    quickFacts: {
      category: "4 Sterne Superior",
      rooms: "122 rooms, 38 suites",
      owner: "Dieter Müller Beteiligungsgesellschaft",
      director: "Johannes Mitterer",
      architect: "Werner Aschaber, Kitzbühel",
      interiorDesign: "Ursula Schelle-Müller, Munich",
      membership: "Preferred Hotels and Resorts L.V.X. Collection",
    },
    verified: true,
    partnerBadge: true,
    seasonOpen: "December",
    seasonClose: "April",
    resortId: "kitzbuehel",
  },

  // ─── Mountain Plaza Hotel ──────────────────────────────────────────────────
  {
    id: "mountain-plaza-davos",
    name: "Mountain Plaza Hotel",
    slug: "mountain-plaza-davos",
    stars: 4,
    category: "4-Sterne-Hotel",
    address: "Talstrasse 3",
    city: "Davos Platz",
    country: "Switzerland",
    countryCode: "CH",
    flag: "🇨🇭",
    coordinates: { lat: 46.7952, lon: 9.8237 },
    phone: "+41 81 415 15 15",
    email: "info@mountainplaza.ch",
    website: "www.davosklostersmountains.ch/de/resorts/mountainplazahotel",
    description: "Mountain Plaza Hotel is Davos's vibrant 4-star hotel in the heart of Davos Platz, steps from the Jakobshorn and the Bolgen sports and events area. With 210 rooms across five categories, a brand-new three-storey fitness centre with panoramic views and Matrix equipment, and a 1,000 m² wellness area with indoor pool, multiple saunas and massages, it delivers everything an active mountain guest needs under one roof. The Plaza Restaurant and Stübli provide all-day dining — the Stübli is famous for its cheese fondue — while the lively Mountain Bar with Vergani wine bar is the social hub of the hotel. The hotel's own ski shop and shuttle bus service to Jakobshorn and Parsenn make it the perfect base for a ski week. Equally popular for corporate events, dance holidays and large group stays.",
    shortDescription: "4-star hotel in the heart of Davos Platz — active mountain base near Jakobshorn with 1,000 m² wellness and 210 rooms.",
    images: [
      "https://media.base44.com/images/public/6a19694d2b38b5e31a976be8/130a486eb_MountainPlazaAussenansichtWinter.jpg",
      "https://media.base44.com/images/public/6a19694d2b38b5e31a976be8/aca82ac96_MountainPlazaPool.jpg",
      "https://media.base44.com/images/public/6a19694d2b38b5e31a976be8/9d7262647_MountainPlazaDampfbad.jpg",
      "https://media.base44.com/images/public/6a19694d2b38b5e31a976be8/dd245eee7_MountainPlazaRestaurant1.jpg",
      "https://media.base44.com/images/public/6a19694d2b38b5e31a976be8/cc9ca1376_MountainPlazaRestaurant.jpg",
      "https://media.base44.com/images/public/6a19694d2b38b5e31a976be8/e8b84735c_MountainPlazaSeminarraum.jpg",
      "https://media.base44.com/images/public/6a19694d2b38b5e31a976be8/dd164151f_MountainPlazaSuite.jpg",
    ],
    priceFrom: 160,
    currency: "CHF",
    rating: 0,
    ratingLabel: "No reviews yet",
    reviewCount: 0,
    amenities: [
      "1,000 m² Wellness", "Indoor Pool", "Multiple Saunas", "Steam Bath", "Massages",
      "3-Storey Fitness Centre", "Ski Shop", "Ski Storage", "Hotel Shuttle",
      "Restaurant", "Stübli", "Mountain Bar", "Wine Bar", "Conference Rooms",
      "Bike Room", "Bike Wash Station", "Free WiFi", "Balcony (selected rooms)",
    ],
    totalRooms: 210,
    totalSuites: 10,
    rooms: [
      { id: "classic", name: "Classic Room", description: "Comfortable classic room with alpine furnishings and mountain views.", size: null, maxGuests: 2, pricePerNight: 160, images: ["https://media.base44.com/images/public/6a19694d2b38b5e31a976be8/dd164151f_MountainPlazaSuite.jpg"], amenities: ["Free WiFi", "Flat-screen TV", "Safe", "Minibar", "Bathroom"], available: true },
      { id: "superior-balkon", name: "Superior Room with Balcony", description: "Spacious superior room with generous balcony overlooking the mountain landscape.", size: null, maxGuests: 2, pricePerNight: 195, images: ["https://media.base44.com/images/public/6a19694d2b38b5e31a976be8/dd164151f_MountainPlazaSuite.jpg"], amenities: ["Free WiFi", "Flat-screen TV", "Safe", "Minibar", "Balcony", "Bathroom"], available: true },
      { id: "suite", name: "Suite", description: "Generously proportioned suite with separate lounge area — the ultimate Mountain Plaza experience.", size: null, maxGuests: 3, pricePerNight: 320, images: ["https://media.base44.com/images/public/6a19694d2b38b5e31a976be8/dd164151f_MountainPlazaSuite.jpg"], amenities: ["Free WiFi", "Flat-screen TV", "Safe", "Minibar", "Separate lounge", "Balcony", "Bathroom"], available: true },
    ],
    restaurants: [
      { name: "Plaza Restaurant", cuisine: "Swiss / International", seats: 120, description: "The main à la carte restaurant of Mountain Plaza, serving Swiss and international cuisine throughout the day.", reservationRequired: false },
      { name: "Stübli", cuisine: "Swiss / Fondue", seats: 40, description: "Cosy smaller restaurant famed for its traditional cheese fondue. Reservations highly recommended.", reservationRequired: true },
      { name: "Mountain Bar", cuisine: "Bar / Lounge", seats: 80, description: "The lively social hub of the hotel with Vergani wine bar, cocktails, and games — perfect for families and groups.", reservationRequired: false },
    ],
    spa: {
      description: "1,000 m² wellness area with indoor swimming pool, multiple saunas including steam bath and thermal bath, relaxation zones and massage treatments. Complemented by a brand-new three-storey fitness centre with MATRIX equipment, panoramic mountain views and zones for strength, endurance and functional training.",
      poolSize: "Indoor pool",
      sqm: 1000,
      saunaTypes: ["Finnish Sauna", "Steam Bath", "Thermal Bath"],
      treatments: "Massages available on-site",
      fitnessEquipment: "MATRIX — three floors, panoramic views",
    },
    events: {
      maxCapacity: 200,
      roomCount: 4,
      largestRoomSqm: null,
      description: "Multiple seminar and event rooms for conferences, corporate events, dance holidays and group celebrations. Popular venue for large events due to its central location near the Jakobshorn and Bolgen.",
      rooms: [
        { name: "Seminarraum 1", capacity: 80, sqm: null, features: "AV equipment, natural daylight" },
        { name: "Seminarraum 2", capacity: 60, sqm: null, features: "Breakout format" },
        { name: "Seminarraum 3", capacity: 40, sqm: null, features: "Boardroom" },
        { name: "Seminarraum 4", capacity: 30, sqm: null, features: "Small group / workshop" },
      ],
    },
    parking: { available: true, type: "On-site parking", pricePerDay: 15, includedInPass: false },
    policies: {
      checkIn: "15:00",
      checkOut: "11:00",
      pets: "On request",
      smoking: "No smoking in rooms",
      children: "Children up to 16 stay free in parents' room",
      cancellation: "Varies by rate",
      deposit: "Credit card required",
    },
    sustainability: {
      certifications: [],
      notes: "Part of Davos Klosters Mountains AG — committed to sustainable mountain tourism.",
    },
    nearbyAttractions: [
      { name: "Jakobshorn gondola", distanceKm: 0.3, type: "Ski Lift" },
      { name: "Bolgen sports area", distanceKm: 0.2, type: "Sports & Events" },
      { name: "Davos Platz centre", distanceKm: 0.1, type: "Shopping & Dining" },
      { name: "Davos Congress Centre", distanceKm: 0.5, type: "Conference" },
    ],
    publicTransport: { nearestStation: "Davos Platz train station", distanceKm: 0.3, shuttleAvailable: true },
    quickFacts: {
      category: "4-Sterne-Hotel",
      rooms: "210 rooms",
      owner: "Davos Klosters Mountains AG",
      membership: "Mountain Resorts Davos Klosters",
    },
    verified: true,
    partnerBadge: true,
    seasonOpen: "December",
    seasonClose: "April",
    resortId: "davos-klosters",
  },

  // ─── Hotel Waldhuus Davos ──────────────────────────────────────────────────
  {
    id: "waldhuus-davos",
    name: "Hotel Waldhuus Davos",
    slug: "waldhuus-davos",
    stars: 4,
    category: "4-Sterne-Superior",
    address: "Mattastrasse 70",
    city: "Davos Dorf",
    country: "Switzerland",
    countryCode: "CH",
    flag: "🇨🇭",
    coordinates: { lat: 46.8103, lon: 9.8275 },
    phone: "+41 81 415 15 15",
    email: "waldhuus@davosklostersmountains.ch",
    website: "www.davosklostersmountains.ch/de/resorts/waldhuus-davos",
    description: "Hotel Waldhuus Davos is a 4-Sterne-Superior chalet hotel sitting directly at the edge of the forest and beside the 18-hole Davos golf course — and in winter, right next to the cross-country ski trails (Langlaufloipe). The hotel's 108 rooms and suites combine warm Graubünden timber with modern comfort. After a day in the mountains, the newly renovated 800 m² wellness area with indoor pool, multiple saunas and massage treatments invites you to unwind. The Waldhuus Restaurant serves breakfast and dinner daily; the Matta Bar with its crackling fireplace is the perfect spot for an aperitif. The Globi Kids Club provides complimentary childcare, making it a favourite with families. Five seminar rooms and a dedicated events programme make it equally popular for weddings, conferences and celebrations. A shuttle bus connects to the Parsenn and Jakobshorn ski areas.",
    shortDescription: "4-star superior chalet hotel on the Davos forest edge — ski trails at the door, 800 m² wellness, family-friendly with Globi Kids Club.",
    images: [
      "https://media.base44.com/images/public/6a19694d2b38b5e31a976be8/3bb9c343a_WaldhuusWellness.jpg",
      "https://media.base44.com/images/public/6a19694d2b38b5e31a976be8/77449c6bf_WaldhuusPool.jpg",
      "https://media.base44.com/images/public/6a19694d2b38b5e31a976be8/df70f582f_WaldhuusRuheraum.jpg",
      "https://media.base44.com/images/public/6a19694d2b38b5e31a976be8/0df46324e_WaldhuusDZ1.jpg",
      "https://media.base44.com/images/public/6a19694d2b38b5e31a976be8/ce5e46686_WaldhuusDZ2.jpg",
      "https://media.base44.com/images/public/6a19694d2b38b5e31a976be8/884c21fba_WaldhuusDZ.jpg",
      "https://media.base44.com/images/public/6a19694d2b38b5e31a976be8/1659e6c72_WaldhuusBadezimmer.jpg",
      "https://media.base44.com/images/public/6a19694d2b38b5e31a976be8/a621a061a_WaldhuusSuite.jpg",
      "https://media.base44.com/images/public/6a19694d2b38b5e31a976be8/9de993a37_WaldhuusFitness.jpg",
      "https://media.base44.com/images/public/6a19694d2b38b5e31a976be8/875692533_WaldhuusJugendraum.jpg",
      "https://media.base44.com/images/public/6a19694d2b38b5e31a976be8/fa9bc73cb_WaldhuusSeminarraum1.jpg",
      "https://media.base44.com/images/public/6a19694d2b38b5e31a976be8/e890739dc_WaldhuusSeminarraum.jpg",
    ],
    priceFrom: 175,
    currency: "CHF",
    rating: 0,
    ratingLabel: "No reviews yet",
    reviewCount: 0,
    amenities: [
      "800 m² Wellness", "Indoor Pool", "Multiple Saunas", "Massages",
      "Fitness Centre", "Globi Kids Club", "Free Childcare",
      "Langlauf / Cross-Country Trails at Door", "Golf Course Adjacent",
      "Hotel Shuttle", "Restaurant", "Matta Bar", "Fireplace Lounge",
      "5 Seminar Rooms", "Wedding Venue", "Free WiFi",
      "Underground Parking with EV Charging", "Ski Storage",
    ],
    totalRooms: 108,
    totalSuites: 12,
    rooms: [
      { id: "dz-comfort", name: "Comfort Double", description: "Warm chalet-style double room with Graubünden timber finishes and mountain views.", size: null, maxGuests: 2, pricePerNight: 175, images: ["https://media.base44.com/images/public/6a19694d2b38b5e31a976be8/0df46324e_WaldhuusDZ1.jpg"], amenities: ["Free WiFi", "Flat-screen TV", "Safe", "Balcony", "Bathroom"], available: true },
      { id: "dz-superior", name: "Superior Double", description: "Generously sized double room with premium alpine furnishings and panoramic balcony.", size: null, maxGuests: 2, pricePerNight: 210, images: ["https://media.base44.com/images/public/6a19694d2b38b5e31a976be8/ce5e46686_WaldhuusDZ2.jpg"], amenities: ["Free WiFi", "Flat-screen TV", "Safe", "Minibar", "Balcony", "Bathroom"], available: true },
      { id: "junior-suite", name: "Junior Suite", description: "Spacious junior suite with separate seating area and timber ceiling beams — the quintessential Waldhuus experience.", size: null, maxGuests: 2, pricePerNight: 295, images: ["https://media.base44.com/images/public/6a19694d2b38b5e31a976be8/a621a061a_WaldhuusSuite.jpg"], amenities: ["Free WiFi", "Flat-screen TV", "Safe", "Minibar", "Separate sitting area", "Balcony"], available: true },
      { id: "waldhuus-suite", name: "Waldhuus Suite", description: "Flagship suite with exposed timber beams, a generous lounge and premium Graubünden alpine atmosphere.", size: null, maxGuests: 4, pricePerNight: 420, images: ["https://media.base44.com/images/public/6a19694d2b38b5e31a976be8/a621a061a_WaldhuusSuite.jpg"], amenities: ["Free WiFi", "Flat-screen TV", "Safe", "Minibar", "Full lounge", "Balcony", "Butler service on request"], available: true },
    ],
    restaurants: [
      { name: "Waldhuus Restaurant", cuisine: "Swiss / Graubünden", seats: 90, description: "The hotel's main restaurant serving a rich breakfast buffet and Swiss-Graubünden dinner menu daily. Warm alpine décor with artisan timber panelling.", reservationRequired: false },
      { name: "Matta Bar", cuisine: "Bar / Lounge", seats: 35, description: "Intimate bar with crackling fireplace — ideal for an aperitif, Graubünden wines or a nightcap after the slopes.", reservationRequired: false },
    ],
    spa: {
      description: "Newly renovated 800 m² wellness area with a large indoor swimming pool, Finnish sauna, steam bath, relaxation rooms with fireplace lounge, and a full massage and treatments menu. Dedicated fitness room. Direct access from the hotel building.",
      poolSize: "Indoor pool",
      sqm: 800,
      saunaTypes: ["Finnish Sauna", "Steam Bath"],
      treatments: "Full massage menu — sports, relaxation, beauty",
      fitnessEquipment: "Cardio and strength equipment",
    },
    events: {
      maxCapacity: 150,
      roomCount: 5,
      largestRoomSqm: null,
      description: "Five seminar rooms for conferences, seminars and events. Popular wedding venue with dedicated event coordination. Ideal for incentive trips and corporate retreats.",
      rooms: [
        { name: "Seminarraum Arve", capacity: 80, sqm: null, features: "Largest room, full AV, natural daylight" },
        { name: "Seminarraum Birke", capacity: 50, sqm: null, features: "Standard conference" },
        { name: "Seminarraum Eiche", capacity: 30, sqm: null, features: "Workshop / breakout" },
        { name: "Seminarraum Fichte", capacity: 20, sqm: null, features: "Boardroom" },
        { name: "Hochzeits-Saal", capacity: 150, sqm: null, features: "Wedding banquet hall" },
      ],
    },
    parking: { available: true, type: "Underground garage with EV charging stations", pricePerDay: 15, includedInPass: false },
    policies: {
      checkIn: "15:00",
      checkOut: "11:00",
      pets: "On request",
      smoking: "No smoking in rooms",
      children: "Two children up to 16 stay free in parents' room — Globi Kids Club complimentary",
      cancellation: "Varies by rate",
      deposit: "Credit card required",
    },
    sustainability: {
      certifications: [],
      notes: "EV charging stations in underground garage. Part of Davos Klosters Mountains AG sustainability programme.",
    },
    nearbyAttractions: [
      { name: "Davos Golf Club (18-hole)", distanceKm: 0.0, type: "Golf" },
      { name: "Langlaufloipe cross-country trails", distanceKm: 0.0, type: "Nordic Skiing" },
      { name: "Parsenn gondola (Davos Dorf)", distanceKm: 1.2, type: "Ski Lift" },
      { name: "Davos Dorf centre", distanceKm: 0.5, type: "Shopping & Dining" },
    ],
    publicTransport: { nearestStation: "Davos Dorf train station", distanceKm: 0.7, shuttleAvailable: true },
    quickFacts: {
      category: "4-Sterne-Superior",
      rooms: "108 rooms and suites",
      owner: "Davos Klosters Mountains AG",
      membership: "Mountain Resorts Davos Klosters",
    },
    verified: true,
    partnerBadge: true,
    seasonOpen: "December",
    seasonClose: "April",
    resortId: "davos-klosters",
  },

  // ─── Parsenn Resort ────────────────────────────────────────────────────────
  {
    id: "parsenn-resort-davos",
    name: "Parsenn Resort",
    slug: "parsenn-resort-davos",
    stars: 4,
    category: "4-Sterne Ferienwohnungen",
    address: "Parsennstrasse 14",
    city: "Davos Dorf",
    country: "Switzerland",
    countryCode: "CH",
    flag: "🇨🇭",
    coordinates: { lat: 46.8150, lon: 9.8240 },
    phone: "+41 81 415 15 15",
    email: "parsennresort@davosklostersmountains.ch",
    website: "www.davosklostersmountains.ch/de/resorts/parsenn-resort",
    description: "Parsenn Resort is the ski-in / ski-out apartment hotel of Davos Klosters Mountains, positioned directly beside the Parsenn valley run so that guests can literally ski back to their door at the end of the day. The 30 modern apartment units — available in 2.5 and 3.5-room configurations — are finished in a clean Nordic style with light timber and warm textiles. Every apartment is fully equipped for self-catering, offering total independence for families and groups. On-site facilities include a modern fitness room and sauna for post-ski recovery. The resort suits guests who want the freedom of apartment living combined with the security of a managed mountain property directly operated by Davos Klosters Mountains AG.",
    shortDescription: "Ski-in/ski-out apartment resort on the Parsenn valley run — 30 Nordic-style apartments, fitness & sauna, total mountain independence.",
    images: [
      "https://media.base44.com/images/public/6a19694d2b38b5e31a976be8/140b98101_ParsennResortSauna.jpg",
    ],
    priceFrom: 220,
    currency: "CHF",
    rating: 0,
    ratingLabel: "No reviews yet",
    reviewCount: 0,
    amenities: [
      "Ski-In / Ski-Out", "Sauna", "Fitness Room",
      "Fully Equipped Kitchen", "Free WiFi", "Parking",
      "Balcony / Terrace", "Ski Storage", "Daily Housekeeping",
    ],
    totalRooms: 30,
    totalSuites: 0,
    rooms: [
      { id: "apt-2-5", name: "2.5-Room Apartment", description: "Modern Nordic-style apartment for 2–3 guests with fully equipped kitchen, living area and balcony. Ski-in / ski-out access.", size: null, maxGuests: 3, pricePerNight: 220, images: ["https://media.base44.com/images/public/6a19694d2b38b5e31a976be8/140b98101_ParsennResortSauna.jpg"], amenities: ["Free WiFi", "Fully equipped kitchen", "Balcony", "Flat-screen TV", "Ski storage", "Sauna access"], available: true },
      { id: "apt-3-5", name: "3.5-Room Apartment", description: "Spacious Nordic apartment for families or groups up to 5 guests with two bedrooms, full kitchen and generous living space. Direct ski access.", size: null, maxGuests: 5, pricePerNight: 320, images: ["https://media.base44.com/images/public/6a19694d2b38b5e31a976be8/140b98101_ParsennResortSauna.jpg"], amenities: ["Free WiFi", "Fully equipped kitchen", "2 bedrooms", "Balcony", "Flat-screen TV", "Ski storage", "Sauna access"], available: true },
    ],
    restaurants: [],
    spa: {
      description: "On-site sauna and modern fitness room for post-ski recovery. Self-catering resort — no restaurant on-site; Davos Dorf village restaurants within easy reach.",
      poolSize: null,
      sqm: null,
      saunaTypes: ["Finnish Sauna"],
      treatments: "None — self-catering resort",
      fitnessEquipment: "Modern fitness room",
    },
    events: {
      maxCapacity: 0,
      roomCount: 0,
      largestRoomSqm: null,
      description: "No dedicated event facilities — residential apartment resort.",
      rooms: [],
    },
    parking: { available: true, type: "On-site parking", pricePerDay: 12, includedInPass: false },
    policies: {
      checkIn: "16:00",
      checkOut: "10:00",
      pets: "No",
      smoking: "No smoking",
      children: "Children of all ages welcome — ideal for families",
      cancellation: "Varies by rate",
      deposit: "Credit card required",
    },
    sustainability: {
      certifications: [],
      notes: "Part of Davos Klosters Mountains AG — direct ski access reduces transport emissions.",
    },
    nearbyAttractions: [
      { name: "Parsenn ski area (ski-in/ski-out)", distanceKm: 0.0, type: "Ski Lift" },
      { name: "Davos Dorf centre", distanceKm: 0.8, type: "Shopping & Dining" },
      { name: "Parsenn gondola (Davos Dorf)", distanceKm: 0.5, type: "Ski Lift" },
    ],
    publicTransport: { nearestStation: "Davos Dorf train station", distanceKm: 1.0, shuttleAvailable: false },
    quickFacts: {
      category: "4-Sterne Ferienwohnungen",
      rooms: "30 apartment units (2.5 and 3.5 rooms)",
      owner: "Davos Klosters Mountains AG",
      membership: "Mountain Resorts Davos Klosters",
    },
    verified: true,
    partnerBadge: true,
    seasonOpen: "December",
    seasonClose: "April",
    resortId: "davos-klosters",
  },
];

export function getHotelById(id) {
  return hotels.find(h => h.id === id) || null;
}