export const hotels = [
  {
    id: "hotel-kitzhof",
    name: "Hotel Kitzhof Mountain Design Resort",
    slug: "hotel-kitzhof",
    stars: 4,
    category: "4 Sterne Superior",
    address: "Schwarzseestrasse 8-10",
    city: "Kitzbühel",
    country: "Austria",
    countryCode: "AT",
    flag: "🇦🇹",
    coordinates: { lat: 47.4472, lon: 12.3913 },
    phone: "+43 5356 63211-0",
    email: "info@hotel-kitzhof.com",
    website: "www.hotel-kitzhof.com",
    description: "Hotel Kitzhof Mountain Design Resort is a 4 Sterne Superior hotel located directly on the city park of Kitzbühel, with panoramic views of the Kitzbüheler Horn and the legendary Hahnenkamm. Just a few minutes walk from the picturesque centre of this famous Tyrolean resort, the hotel combines stylish alpine design with genuine Tyrolean warmth. The design concept by Munich interior designer Ursula Schelle-Müller blends generous use of glass and natural daylight with mountain larch wood floors, reclaimed timber panelling, modern furniture upholstered in grey and red loden, open fireplaces, antler decorations and designer lighting. The result redefines Tyrolean Gemütlichkeit for the contemporary traveller. Member of Preferred Hotels and Resorts L.V.X. Collection.",
    shortDescription: "4-star superior mountain design resort in Kitzbühel — steps from the Hahnenkamm, walk to the lifts.",
    logo: "https://media.base44.com/images/public/69f1c737747c83c0b091a543/1d289c8f4_Bildschirmfoto_30-4-2026_205344_.jpg",
    images: [
      "https://media.base44.com/images/public/69f1c737747c83c0b091a543/18c29298b_AuenansichtfrontHotelKitzhof.jpg",
      "https://media.base44.com/images/public/69f1c737747c83c0b091a543/0bd8137f1_AuenansichtGartenHotelKitzhof.jpg",
      "https://media.base44.com/images/public/69f1c737747c83c0b091a543/8fca7a304_AuenansichtTerrasse2HotelKitzhof.jpg",
      "https://media.base44.com/images/public/69f1c737747c83c0b091a543/b750cb336_PoolHotelKitzhof.jpg",
      "https://media.base44.com/images/public/69f1c737747c83c0b091a543/a28bfe685_PoolLiegebereichHotelKitzhof.jpg",
      "https://media.base44.com/images/public/69f1c737747c83c0b091a543/52d461bad_RuhebereichHotelKitzhof.jpg",
      "https://media.base44.com/images/public/69f1c737747c83c0b091a543/b039fe118_KitzhofRestaurantHotelKitzhof.jpg",
      "https://media.base44.com/images/public/69f1c737747c83c0b091a543/92656e197_KaminstubeHotelKitzhof.jpg",
      "https://media.base44.com/images/public/69f1c737747c83c0b091a543/8a51bc3a6_VinothekHotelKitzhof.jpg",
      "https://media.base44.com/images/public/69f1c737747c83c0b091a543/e71315b1e_KitzLoungeKaminbereichHotelKitzhof.jpg",
      "https://media.base44.com/images/public/69f1c737747c83c0b091a543/6072023dc_ChampagnerfrhstckaufderTerrasseHotelKitzhof.jpg",
      "https://media.base44.com/images/public/69f1c737747c83c0b091a543/00ad3ef63_Terrasse2HotelKitzhof.jpg",
      "https://media.base44.com/images/public/69f1c737747c83c0b091a543/40945f6bb_DZSuperiorKitzbhelHotelKitzhof.jpg",
      "https://media.base44.com/images/public/69f1c737747c83c0b091a543/b97aefb97_AlpinSuiteHotelKitzhof.jpg",
      "https://media.base44.com/images/public/69f1c737747c83c0b091a543/0a316aaaf_AlpinSuite2HotelKitzhof.jpg",
      "https://media.base44.com/images/public/69f1c737747c83c0b091a543/9edcff9dc_StudioHotelKitzhof.jpg",
      "https://media.base44.com/images/public/69f1c737747c83c0b091a543/863e5ddd0_StudioSuite2HotelKitzhof.jpg",
      "https://media.base44.com/images/public/69f1c737747c83c0b091a543/eb142cddd_GardenSuiteHotelKitzhof.jpg",
      "https://media.base44.com/images/public/69f1c737747c83c0b091a543/580829ff4_KitzhofSuite2HotelKitzhof.jpg",
    ],
    priceFrom: 195,
    currency: "EUR",
    rating: 0,
    ratingLabel: "No reviews yet",
    reviewCount: 0,
    amenities: [
      "Indoor Pool", "Spa 900m²", "Free WiFi", "Restaurant", "Bar / Lounge",
      "Fitness Centre", "Underground Parking", "Conference Rooms",
      "Ski Storage", "Hotel Shuttle", "Sauna Landscape", "Fireplace Lounge",
      "Garden", "Terrace", "Room Service", "Concierge", "Wine Cellar",
    ],
    totalRooms: 122,
    totalSuites: 38,
    rooms: [
      { id: "dz-kitz", name: "Double Superior Kitzbühel", description: "Panoramic views of Kitzbühel and surroundings. Alpine design with mountain larch floors.", size: null, maxGuests: 2, pricePerNight: 195, images: ["https://media.base44.com/images/public/69f1c737747c83c0b091a543/40945f6bb_DZSuperiorKitzbhelHotelKitzhof.jpg"], amenities: ["Free WiFi", "Minibar", "Safe", "Flat-screen TV", "Raindance shower", "Telephone"], available: true },
      { id: "dz-streif", name: "Double Superior Streif", description: "Named after the legendary Hahnenkamm Streif downhill course. Premium alpine finishes.", size: null, maxGuests: 2, pricePerNight: 215, images: ["https://media.base44.com/images/public/69f1c737747c83c0b091a543/40945f6bb_DZSuperiorKitzbhelHotelKitzhof.jpg"], amenities: ["Free WiFi", "Minibar", "Safe", "Flat-screen TV", "Raindance shower", "Telephone"], available: true },
      { id: "dz-lebenberg", name: "Double Superior Lebenberg", description: "Views of the Lebenberg castle. Warm alpine atmosphere with reclaimed timber detail.", size: null, maxGuests: 2, pricePerNight: 205, images: ["https://media.base44.com/images/public/69f1c737747c83c0b091a543/40945f6bb_DZSuperiorKitzbhelHotelKitzhof.jpg"], amenities: ["Free WiFi", "Minibar", "Safe", "Flat-screen TV", "Raindance shower", "Telephone"], available: true },
      { id: "junior-suite", name: "Junior Suite", description: "Spacious junior suite with separate living area. Ideal for couples seeking extra space.", size: null, maxGuests: 2, pricePerNight: 285, images: ["https://media.base44.com/images/public/69f1c737747c83c0b091a543/b97aefb97_AlpinSuiteHotelKitzhof.jpg"], amenities: ["Free WiFi", "Minibar", "Safe", "Flat-screen TV", "Raindance shower", "Separate living area"], available: true },
      { id: "studio", name: "Studio", description: "Top-floor studio with Velux skylights offering views of the mountain landscape.", size: null, maxGuests: 2, pricePerNight: 265, images: ["https://media.base44.com/images/public/69f1c737747c83c0b091a543/9edcff9dc_StudioHotelKitzhof.jpg"], amenities: ["Free WiFi", "Minibar", "Safe", "Flat-screen TV", "Skylight windows", "Raindance shower"], available: true },
      { id: "alpin-suite", name: "Alpin Suite", description: "Generous suite with separate living room and full alpine design concept.", size: null, maxGuests: 3, pricePerNight: 345, images: ["https://media.base44.com/images/public/69f1c737747c83c0b091a543/b97aefb97_AlpinSuiteHotelKitzhof.jpg"], amenities: ["Free WiFi", "Minibar", "Safe", "Flat-screen TV", "Separate living room", "Raindance shower"], available: true },
      { id: "studio-suite", name: "Studio Suite", description: "Top-floor suite with premium finishes, skylights and panoramic mountain views.", size: null, maxGuests: 3, pricePerNight: 365, images: ["https://media.base44.com/images/public/69f1c737747c83c0b091a543/863e5ddd0_StudioSuite2HotelKitzhof.jpg"], amenities: ["Free WiFi", "Minibar", "Safe", "Flat-screen TV", "Skylight", "Raindance shower"], available: true },
      { id: "lebenberg-suite", name: "Lebenberg Suite", description: "Named after the Lebenberg — generous suite with classic Tyrolean mountain views.", size: null, maxGuests: 4, pricePerNight: 385, images: ["https://media.base44.com/images/public/69f1c737747c83c0b091a543/0a316aaaf_AlpinSuite2HotelKitzhof.jpg"], amenities: ["Free WiFi", "Minibar", "Safe", "Flat-screen TV", "Separate living area", "Raindance shower"], available: true },
      { id: "garden-suite", name: "Garden Suite", description: "Private garden access. Built in 2019 and extended 2023. East wing location with serene views.", size: null, maxGuests: 4, pricePerNight: 425, images: ["https://media.base44.com/images/public/69f1c737747c83c0b091a543/eb142cddd_GardenSuiteHotelKitzhof.jpg"], amenities: ["Free WiFi", "Minibar", "Safe", "Flat-screen TV", "Private garden", "Raindance shower"], available: true },
      { id: "kitzhof-suite", name: "Kitzhof Suite", description: "The hotel's flagship suite. Suitable for boardroom use. Ultimate luxury in Kitzbühel.", size: null, maxGuests: 4, pricePerNight: 550, images: ["https://media.base44.com/images/public/69f1c737747c83c0b091a543/580829ff4_KitzhofSuite2HotelKitzhof.jpg"], amenities: ["Free WiFi", "Minibar", "Safe", "Flat-screen TV", "Boardroom setup possible", "Raindance shower", "Butler service"], available: true },
    ],
    restaurants: [
      { name: "Weisser Hirsch", cuisine: "Austrian / International", seats: 100, description: "The main restaurant of Hotel Kitzhof, offering Austrian and international cuisine in an elegant alpine setting.", reservationRequired: false },
      { name: "Kaminstube", cuisine: "Alpine", seats: 65, description: "Cosy fireplace room serving hearty alpine dishes. Ideal for evenings after a day on the slopes.", reservationRequired: true },
      { name: "Kitz Alm", cuisine: "Tyrolean", seats: 50, description: "Rustic mountain hut-style dining featuring traditional Tyrolean specialities.", reservationRequired: false },
      { name: "Hornstube", cuisine: "Fine Dining", seats: 30, description: "Intimate fine dining room with a focused seasonal menu and attentive service.", reservationRequired: true },
      { name: "Vinothek", cuisine: "Wine Bar", seats: 16, description: "A walk-in wine cellar featuring an exceptional selection of Austrian and international wines.", reservationRequired: false },
      { name: "Jagdstube", cuisine: "Private Dining", seats: 15, description: "Exclusive private dining room in hunting lodge style — ideal for special occasions.", reservationRequired: true },
      { name: "Kitz Lounge", cuisine: "Bar", seats: 40, description: "The social heart of the hotel — cocktails, après-ski, and a warm fireplace atmosphere.", reservationRequired: false },
    ],
    spa: {
      description: "The Kitz Spa spans 900 sqm with a 15x5m indoor pool with experience showers, relaxation area and winter garden. Sauna landscape includes steam bath, brine steam bath, Swiss pine sauna and sanarium with relaxation room and fireplace. Five treatment rooms with Susanne Kaufmann products. Life Fitness gym equipment.",
      poolSize: "15 × 5 m",
      sqm: 900,
      saunaTypes: ["Steam bath", "Brine steam bath", "Swiss pine sauna (Zirbensauna)", "Sanarium"],
      treatments: "5 treatment rooms — Susanne Kaufmann product range",
      fitnessEquipment: "Life Fitness branded equipment",
    },
    events: {
      maxCapacity: 400,
      roomCount: 9,
      largestRoomSqm: 340,
      description: "The Kitzbüheler Alpen conference area comprises five rooms on the garden level, four with direct garden access. Can be combined into one large hall of 340 sqm. Also Davos, Lech, St. Moritz rooms and Kitzhof Suite for smaller meetings.",
      rooms: [
        { name: "Kitzbüheler Alpen", capacity: 400, sqm: 340, features: "5 combinable rooms, direct garden access" },
        { name: "Davos", capacity: 40, sqm: 60, features: "Breakout room" },
        { name: "Lech", capacity: 40, sqm: 60, features: "Breakout room" },
        { name: "St. Moritz", capacity: 40, sqm: 60, features: "Breakout room" },
        { name: "Kitzhof Suite", capacity: 20, sqm: null, features: "Boardroom / private meeting" },
      ],
    },
    parking: { available: true, type: "Underground garage, on-site", pricePerDay: 18, includedInPass: false },
    policies: {
      checkIn: "15:00",
      checkOut: "11:00",
      pets: "On request",
      smoking: "No smoking in rooms — designated outdoor areas only",
      children: "Children of all ages welcome",
      cancellation: "Varies by rate — see booking conditions at time of reservation",
      deposit: "Credit card required at check-in",
    },
    sustainability: {
      certifications: [],
      notes: "Committed to local Austrian produce and regional suppliers. Energy efficiency measures ongoing.",
    },
    nearbyAttractions: [
      { name: "Hahnenkamm gondola", distanceKm: 0.6, type: "Ski Lift" },
      { name: "Kitzbühel town centre", distanceKm: 0.3, type: "Shopping & Dining" },
      { name: "Kitzbüheler Horn cable car", distanceKm: 1.2, type: "Ski Lift" },
      { name: "Golf Club Kitzbühel", distanceKm: 2, type: "Golf" },
    ],
    publicTransport: { nearestStation: "Kitzbühel train station", distanceKm: 0.8, shuttleAvailable: true },
    history: [
      { year: "1993/94", event: "Purchase and conversion of the old Hotel Hirzinger Hof" },
      { year: "December 1994", event: "Opening as Astron Sporthotel Kitzbühel" },
      { year: "2005", event: "Repositioned as individual hotel under the name Hotel Kitzhof" },
      { year: "2005–2008", event: "Continuous expansion, renovation and conversion works to the current Hotel Kitzhof Mountain Design Resort" },
      { year: "2014", event: "Top floor expansion adding Studio room category" },
      { year: "2015", event: "Top floor expansion adding Alpin Suites, Studio Suites and Lebenberg Suites" },
      { year: "2016", event: "New Double Superior Streif rooms and Junior Suites" },
      { year: "2017", event: "Expansion of sauna landscape and relaxation area" },
      { year: "2018", event: "Refresh of Double Superior Lebenberg and Superior Kitzbühel rooms, Lebenberg Suites, redesign of Kitz Lounge" },
      { year: "2019", event: "East wing conversion, new Garden Suites completed, new modern fitness wing built" },
      { year: "2023", event: "Room renovations, two additional Garden Suites built, new lobby and conference area completed" },
    ],
    quickFacts: {
      category: "4 Sterne Superior",
      rooms: "122 rooms, 38 suites",
      owner: "Dieter Müller Beteiligungsgesellschaft",
      director: "Johannes Mitterer",
      architect: "Werner Aschaber, Kitzbühel",
      interiorDesign: "Ursula Schelle-Müller, Munich",
      membership: "Preferred Hotels and Resorts L.V.X. Collection",
    },
    verified: true,
    partnerBadge: true,
    seasonOpen: "December",
    seasonClose: "April",
  },
];

export function getHotelById(id) {
  return hotels.find(h => h.id === id) || null;
}