/**
 * Verified partner ski school profiles.
 * Each school can be linked to one or more resort IDs via `resortIds`.
 */
export const SKI_SCHOOLS = [
  {
    id: "skischule-reith",
    name: "Skischule Reith bei Kitzbühel",
    tagline: "Die blaue Schule — Ski · Verleih · Service",
    location: "Reith bei Kitzbühel, Tyrol, Austria",
    address: "Kirchweg 7, 6370 Reith bei Kitzbühel",
    phone: "+43 5356 654 96",
    email: "office@skischule-reith.at",
    website: "https://www.skischule-reith.at",
    // Resorts this school serves (Reith is directly adjacent to Kitzbühel,
    // also serves St. Johann area and Fieberbrunn via Kitzbühel ski region)
    resortIds: ["kitzbuehel", "fieberbrunn"],
    instructorCount: 150,
    languages: ["🇦🇹 German", "🇬🇧 English"],
    disciplines: ["Skiing", "Snowboard", "Cross-country / Langlauf", "Freeride"],
    rating: 4.9,
    reviews: 320,
    verified: true,
    // PeakXP partner badge
    partner: true,
    heroImage: "https://media.base44.com/images/public/6a19694d2b38b5e31a976be8/b42c7285d_DJI_0133.jpg",
    images: [
      "https://media.base44.com/images/public/6a19694d2b38b5e31a976be8/b42c7285d_DJI_0133.jpg",
      "https://media.base44.com/images/public/6a19694d2b38b5e31a976be8/1c15db4b4_Skischule_Winter.jpg",
      "https://media.base44.com/images/public/6a19694d2b38b5e31a976be8/dcfbe1064_AS-PHOTO-231203-1199-web2048px72dpi.jpg",
      "https://media.base44.com/images/public/6a19694d2b38b5e31a976be8/76878d1fe_AS-PHOTO-231203-1511-web2048px72dpi.jpg",
      "https://media.base44.com/images/public/6a19694d2b38b5e31a976be8/b6701dd84_AY5I5181.jpg",
      "https://media.base44.com/images/public/6a19694d2b38b5e31a976be8/609167fed_AY5I5493.jpg",
      "https://media.base44.com/images/public/6a19694d2b38b5e31a976be8/f2af1a8fa_GruppenfotoLogoneu.jpg",
    ],
    description: "Skischule Reith bei Kitzbühel — die blaue Schule — has been sharing the joy of skiing in one of the world's most celebrated ski regions for generations. Up to 150 fully qualified ski, snowboard and cross-country instructors are ready to guide guests of all ages and abilities across the slopes of the legendary Kitzbühel ski area. The school's own Reither Skiwiese — with a 1,000m² Kinderland, 4 conveyor belt lifts, a 100m bob run and free ski lift — is the perfect, safe, car-free environment to take first turns on snow. For advanced skiers and freeriders, the instructors explore the full extent of the Kitzbühel ski region, repeatedly voted the world's best. Director Josef Dagn (state-certified ski instructor, mountain and ski guide, cross-country instructor) and his son Andreas lead a passionate team delivering the highest standard of instruction.",
    highlights: [
      "1,000m² Kinderland with free ski lift and 4 conveyor lifts",
      "100m bob run on the Reither Skiwiese",
      "Free parking at the school base",
      "Rennschule (race school) — training on the Hahnenkamm course",
      "Freeride private lessons with specialist guides",
      "Snowboard, cross-country and ski touring private instruction",
      "Bambini Club from age 2 (with advance booking)",
      "Equipment rental and ski service on-site",
      "Perfect ski bus connections to Kitzbühel",
    ],
    offerings: [
      {
        category: "Kinderland & Bambini",
        items: [
          { name: "Bambini Club (age 2–4) — half day", priceFrom: 50, unit: "per child" },
          { name: "Bambini Club (age 2–4) — full day", priceFrom: 85, unit: "per child" },
          { name: "Group lesson (age 3) — half day", priceFrom: 40, unit: "per child" },
        ],
      },
      {
        category: "Group Courses",
        items: [
          { name: "Group — half day (ski meadow)", priceFrom: 60, unit: "per person" },
          { name: "Group — 1 day", priceFrom: 90, unit: "per person" },
          { name: "Group — 3 days", priceFrom: 240, unit: "per person" },
          { name: "Group — 5 days", priceFrom: 345, unit: "per person" },
          { name: "Group — 6 days", priceFrom: 390, unit: "per person" },
        ],
      },
      {
        category: "Private Lessons (Ski, Snowboard, Cross-country)",
        items: [
          { name: "Private — 2 hours (off-peak)", priceFrom: 220, unit: "per lesson" },
          { name: "Private — 2 hours (peak)", priceFrom: 230, unit: "per lesson" },
          { name: "Private — 1 day 4h (off-peak)", priceFrom: 310, unit: "per day" },
          { name: "Private — 1 day 4h (peak)", priceFrom: 340, unit: "per day" },
          { name: "Private — 6 days 4h/day (off-peak)", priceFrom: 1800, unit: "total" },
          { name: "Private — 6 days 4h/day (peak)", priceFrom: 1920, unit: "total" },
          { name: "Additional person per day", priceFrom: 30, unit: "per person" },
        ],
      },
      {
        category: "Freeride Private",
        items: [
          { name: "Freeride — 1 day", priceFrom: 450, unit: "per lesson" },
          { name: "Freeride — 3 days", priceFrom: 1350, unit: "total" },
          { name: "Freeride — 6 days", priceFrom: 2700, unit: "total" },
          { name: "Additional person per day", priceFrom: 30, unit: "per person" },
        ],
      },
    ],
    // Summary for ski school tab
    groupLessonFrom: 60,
    privateLessonFrom: 220,
    freeridefrom: 450,
    kidsGroupFrom: 40,
    rentalAvailable: true,
    serviceAvailable: true,
    // Peak / off-peak note
    priceNote: "Peak season: 20 Dec – 11 Jan & 31 Jan – 8 Mar. Off-peak: all other dates. Group prices are per person for groups of 5–8.",
    cancellationPolicy: "Free cancellation up to 48 hours before lesson start.",
    director: {
      name: "Josef Dagn",
      role: "Director & Head Instructor",
      qualifications: ["State-certified ski instructor", "State-certified mountain & ski guide", "Cross-country instructor"],
    },
  },
  {
    id: "skischule-silvia-grillitsch",
    name: "Ski- & Snowboardschule Silvia Grillitsch & Partner",
    tagline: "Obertauern's leading ski & snowboard school",
    location: "Obertauern, Salzburg, Austria",
    address: "A-5562 Obertauern",
    phone: "+43 6456 7462",
    website: "https://www.skischule-obertauern.at",
    resortIds: ["obertauern"],
    disciplines: ["Skiing", "Snowboard", "Freeride", "Airboarding"],
    rating: 4.9,
    reviews: 210,
    verified: true,
    partner: false,
    heroImage: "https://media.base44.com/images/public/6a19694d2b38b5e31a976be8/b84a745d6_image.png",
    images: [
      "https://media.base44.com/images/public/6a19694d2b38b5e31a976be8/b84a745d6_image.png",
    ],
    description: "Ski- & Snowboardschule Silvia Grillitsch & Partner is one of Obertauern's most established schools, offering ski and snowboard lessons for all levels from absolute beginners to advanced freeriders. Also offers Airboarding — Obertauern's unique high-speed air-cushion body boarding experience.",
    highlights: [
      "Ski & snowboard lessons all levels",
      "Freeride & off-piste courses with LVS training",
      "Airboarding school",
      "Kids ski courses from age 3",
    ],
    groupLessonFrom: 45,
    privateLessonFrom: 140,
    cancellationPolicy: "Contact school directly.",
  },
  {
    id: "skischule-frau-holle",
    name: "Ski- & Snowboardschule Frau Holle",
    tagline: "Ski & Snowboard in Obertauern",
    location: "Obertauern, Salzburg, Austria",
    address: "A-5562 Obertauern",
    phone: "+43 6456 72009 10",
    resortIds: ["obertauern"],
    disciplines: ["Skiing", "Snowboard"],
    rating: 4.8,
    reviews: 156,
    verified: true,
    partner: false,
    heroImage: "https://media.base44.com/images/public/6a19694d2b38b5e31a976be8/b84a745d6_image.png",
    images: [
      "https://media.base44.com/images/public/6a19694d2b38b5e31a976be8/b84a745d6_image.png",
    ],
    description: "Ski- & Snowboardschule Frau Holle offers quality ski and snowboard instruction in Obertauern for all ages and abilities, with a warm and personal approach.",
    highlights: ["Group & private ski lessons", "Snowboard instruction", "Kids programmes"],
    groupLessonFrom: 45,
    privateLessonFrom: 140,
  },
  {
    id: "skischule-koch-obertauern",
    name: "Skischule Koch",
    tagline: "Ski & Snowbike — Obertauern",
    location: "Obertauern, Salzburg, Austria",
    address: "A-5562 Obertauern",
    phone: "+43 6456 73686",
    resortIds: ["obertauern"],
    disciplines: ["Skiing", "Snowbike"],
    rating: 4.7,
    reviews: 98,
    verified: true,
    partner: false,
    heroImage: "https://media.base44.com/images/public/6a19694d2b38b5e31a976be8/b84a745d6_image.png",
    images: [
      "https://media.base44.com/images/public/6a19694d2b38b5e31a976be8/b84a745d6_image.png",
    ],
    description: "Skischule Koch is Obertauern's go-to school for snowbike rental and instruction — a unique Obertauern speciality. Also offers ski lessons and ski touring.",
    highlights: ["Snowbike school & rental", "Ski lessons all levels", "Ski touring on request"],
    groupLessonFrom: 45,
    privateLessonFrom: 140,
  },
  {
    id: "skischule-krallinger",
    name: "Ski- & Snowboardschule Krallinger",
    tagline: "Ski & Snowboard Obertauern",
    location: "Obertauern, Salzburg, Austria",
    address: "A-5562 Obertauern",
    phone: "+43 6456 72007",
    resortIds: ["obertauern"],
    disciplines: ["Skiing", "Snowboard"],
    rating: 4.8,
    reviews: 122,
    verified: true,
    partner: false,
    heroImage: "https://media.base44.com/images/public/6a19694d2b38b5e31a976be8/b84a745d6_image.png",
    images: [
      "https://media.base44.com/images/public/6a19694d2b38b5e31a976be8/b84a745d6_image.png",
    ],
    description: "Ski- & Snowboardschule Krallinger offers expert ski and snowboard tuition for all levels. Known for attentive instruction and small group sizes.",
    highlights: ["Ski & snowboard all levels", "Small groups", "Kids & adult courses"],
    groupLessonFrom: 45,
    privateLessonFrom: 140,
  },
  {
    id: "skischule-top-obertauern",
    name: "Ski- & Snowboardschule Top",
    tagline: "Top instruction in Obertauern",
    location: "Obertauern, Salzburg, Austria",
    address: "A-5562 Obertauern",
    phone: "+43 6456 7678",
    resortIds: ["obertauern"],
    disciplines: ["Skiing", "Snowboard"],
    rating: 4.7,
    reviews: 89,
    verified: true,
    partner: false,
    heroImage: "https://media.base44.com/images/public/6a19694d2b38b5e31a976be8/b84a745d6_image.png",
    images: [
      "https://media.base44.com/images/public/6a19694d2b38b5e31a976be8/b84a745d6_image.png",
    ],
    description: "Ski- & Snowboardschule Top delivers professional ski and snowboard courses in Obertauern, focusing on technical progression and fun for all ages.",
    highlights: ["Ski & snowboard lessons", "Technique focused", "All ages & levels"],
    groupLessonFrom: 45,
    privateLessonFrom: 140,
  },
  {
    id: "local-guides-am-tauern",
    name: "Local Guides am Tauern — Skischule & Freeride Center",
    tagline: "Obertauern's freeride specialists",
    location: "Obertauern, Salzburg, Austria",
    address: "A-5562 Obertauern",
    phone: "+43 664 1634927",
    resortIds: ["obertauern"],
    disciplines: ["Skiing", "Freeride", "Ski Touring", "Off-piste"],
    rating: 4.9,
    reviews: 78,
    verified: true,
    partner: false,
    heroImage: "https://media.base44.com/images/public/6a19694d2b38b5e31a976be8/b84a745d6_image.png",
    images: [
      "https://media.base44.com/images/public/6a19694d2b38b5e31a976be8/b84a745d6_image.png",
    ],
    description: "Local Guides am Tauern is Obertauern's premier freeride centre and ski school. Their expert local guides know every powder stash and off-piste line — from the Tiefschnee-Runs off Hochalmbahn and Kringsalmbahn to ski touring in the surrounding Radstädter Tauern. Freeride courses include LVS beacon training, avalanche safety, snow science, and terrain assessment.",
    highlights: [
      "Freeride & off-piste courses — LVS, avalanche safety, snow science",
      "Ski touring on request — Radstädter Tauern",
      "SAAC avalanche camp coordination with TVB Obertauern",
      "Local expert knowledge of all four-aspect terrain",
      "Gamsleiten 2 expert line guidance",
      "Small groups for maximum personalised instruction",
    ],
    groupLessonFrom: 65,
    privateLessonFrom: 180,
    cancellationPolicy: "Contact school directly.",
  },
  {
    id: "snowboardschule-blue-tomato",
    name: "Snowboardschule Blue Tomato",
    tagline: "Obertauern's dedicated snowboard school",
    location: "Obertauern, Salzburg, Austria",
    address: "A-5562 Obertauern",
    phone: "+43 6456 20036",
    resortIds: ["obertauern"],
    disciplines: ["Snowboard", "Freestyle"],
    rating: 4.8,
    reviews: 134,
    verified: true,
    partner: false,
    heroImage: "https://media.base44.com/images/public/6a19694d2b38b5e31a976be8/b84a745d6_image.png",
    images: [
      "https://media.base44.com/images/public/6a19694d2b38b5e31a976be8/b84a745d6_image.png",
    ],
    description: "Snowboardschule Blue Tomato is Obertauern's specialist snowboard school — the only dedicated snowboard school in the resort. Beginners to advanced, freestyle, freeriding and off-piste carving.",
    highlights: ["Dedicated snowboard school", "Beginners to advanced", "Freestyle & freeride", "All ages"],
    groupLessonFrom: 50,
    privateLessonFrom: 150,
  },
  {
    id: "langlaufschule-gnadenalm",
    name: "Langlaufschule Gnadenalm",
    tagline: "Cross-country skiing in the Tauern",
    location: "Gnadenalm, near Obertauern, Salzburg, Austria",
    address: "Gnadenalm, A-5562 Obertauern region",
    phone: "+43 664 4139518",
    resortIds: ["obertauern"],
    disciplines: ["Cross-country / Nordic", "Classic", "Skating"],
    rating: 4.8,
    reviews: 62,
    verified: true,
    partner: false,
    heroImage: "https://media.base44.com/images/public/6a19694d2b38b5e31a976be8/b84a745d6_image.png",
    images: [
      "https://media.base44.com/images/public/6a19694d2b38b5e31a976be8/b84a745d6_image.png",
    ],
    description: "Langlaufschule Gnadenalm runs Obertauern's dedicated cross-country skiing school from the Gnadenalm — 5km north of the resort. Instruction in both classic and skating style on the 20km Gnadenalmloipe. Also organises laser biathlon sessions and night sledging.",
    highlights: [
      "Classic & skating style cross-country instruction",
      "20km Gnadenalmloipe trail access",
      "Laser biathlon sessions at the Gnadenalm range",
      "Night sledging at Gnadenalm (1.5km run with snowmobile uplift)",
      "Horse-drawn sleigh rides arranged nearby",
    ],
    groupLessonFrom: 40,
    privateLessonFrom: 120,
  },
];

export function getSkiSchoolsByResortId(resortId) {
  return SKI_SCHOOLS.filter(s => s.resortIds.includes(resortId));
}